### ISSUE TITLE
Move Web chat CSS files to CDN

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#806]
https://storage.cloud.google.com/articulate-webchat/articulate-webchat-0.0.1.css
and 
https://storage.cloud.google.com/articulate-webchat/articulate-webchat-0.0.1.js

are not accessible

**Comment by wrathagom** [comment]
@mordebip master isn't considered usable. These features are brand new an un-tested. These files need to move to a CDN before they'll be usable from a wide audience.

**Comment by mordebip** [comment]
Yeah understood and it would be great if it was available to help with the tests and the possible improvements.

**Comment by mordebip** [comment]
Trying different elements on the webchat, and i find out that the 
http://****/api/connection/{ID}/external

ps : this error happens with and without authentication enabled (tried it on two different servers (always using docker built from master)

is giving an 500 error
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred"
}

`g: handler, error 
    Error: Not Found
    at internals.notFound (/usr/src/app/node_modules/hapi/lib/core.js:618:16)
    at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/usr/src/app/node_modules/hapi/lib/handler.js:50:48)
    at exports.execute (/usr/src/app/node_modules/hapi/lib/handler.js:35:36)
    at Request._lifecycle (/usr/src/app/node_modules/hapi/lib/request.js:263:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{ error:
   { Error: Request failed with status code 404
       at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
       at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:18:12)
       at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:201:11)
       at IncomingMessage.emit (events.js:203:15)
       at IncomingMessage.EventEmitter.emit (domain.js:448:20)
       at endReadableNT (_stream_readable.js:1129:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)

     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        baseURL: 'http://rasa:5000',
        url: 'http://rasa:5000/parse',
        data:
         '{"project":"xxxxxxxx","model":"default_just_er_e367af7b-1ab7-af0f-e18d-2e322357d532"}' },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST /parse HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 86\r\nHost: rasa:5000\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/parse',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     response:
      { status: 404,
        statusText: 'Not Found',
        headers: [Object],
        config: [Object],
        request: [ClientRequest],
        data: [Object] } },
  message: null }
{ error:
   { isHandled: true,
     statusCode: 500,
     message: 'Request failed with status code 404' },
  message: null }
Debug: handler, error 
    Error: Request failed with status code 404
    at Object.<anonymous> (/usr/src/app/lib/channels/chat-widget/post.js:33:14)
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/usr/src/app/lib/channels/chat-widget/post.js:7:103)
    at _throw (/usr/src/app/lib/channels/chat-widget/post.js:9:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Debug: internal, error 
    Error: Request failed with status code 404
    at Object.<anonymous> (/usr/src/app/lib/channels/chat-widget/post.js:33:14)
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/usr/src/app/lib/channels/chat-widget/post.js:7:103)
    at _throw (/usr/src/app/lib/channels/chat-widget/post.js:9:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

exploring it to see if i can help by including https://github.com/mrbot-ai/rasa-webchat or

**Comment by mordebip** [comment]
This is most likely a rasa issue 
 [15/Jul/2019:12:40:14 +0000] "POST /parse HTTP/1.1" 404 50 "-" "axios/0.18.0"

**Comment by wrathagom** [comment]
This isn't related to the CDN files being available. I think you already have another issue being addressed by @malave for the 500 errors.

**Comment by mordebip** [comment]
Yes i'm still exploring :p
for this one, it might be solved by updating rasa.

**Comment by mordebip** [comment]
Update :
after adding a sessionId to the post query
the response is on response.processedResponses[0].textResponse

by updating the  post file to
  const response =await agentService.converse({ ...
      
but i'm still getting

```
{ error:
   Error: Invalid search parameters: Searching for a unique (type "string") with a non-string value is not supported.
       at Object.keys.map (/usr/src/app/node_modules/nohm/ts/model.ts:1779:19)
       at Array.map (<anonymous>)
       at CreatedClass.createStructuredSearchOptions (/usr/src/app/node_modules/nohm/ts/model.ts:1763:34)
       at CreatedClass.find (/usr/src/app/node_modules/nohm/ts/model.ts:1700:37)
       at find (/usr/src/app/server/plugins/redis/lib/base-model.js:233:32)
       at Generator.next (<anonymous>)
       at asyncGeneratorStep (/usr/src/app/server/plugins/redis/lib/base-model.js:15:103)
       at _next (/usr/src/app/server/plugins/redis/lib/base-model.js:17:194)
       at /usr/src/app/server/plugins/redis/lib/base-model.js:17:364
       at new Promise (<anonymous>),
  message: null }
```

**Comment by mordebip** [comment]
Found a way to remove the auth from the extrernal
added auth: false, before the handler on connection.post.route, but still have some errors to fix

**Comment by wrathagom** [comment]
@dcalvom had you already removed auth from the ubiquity endpoints?

**Comment by dcalvom** [comment]
Not yet @wrathagom

**Comment by dcalvom** [comment]
We still need to move this to a proper CDN. @wrathagom any suggestion for this?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b12b62e55dc031a9d612aa9a618c853b082037b8
